version: "3"
services:
  ramen_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    image: ramen_server
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    depends_on:
      - ramen_db
    container_name: ramen_server
    environment:
      - "DATABASE_HOST=ramen_db"
      - "DATABASE_PORT=5432"
      - "DATABASE_USER=ramens"
      - "DATABASE_PASSWORD=farmas0713"
    env_file: variables.local.env

  ramen_db:
    image: postgres:10
    container_name: "ramen_db"
    ports:
      - "3306:5432"
    volumes:
      - ramen_db:/var/lib/postgresql/data
      - ./docker_postgres:/docker-entrypoint-initdb.d
volumes:
  ramen_db:
